version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:latest
    restart: unless-stopped
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      #- ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_PASSWORD=vCyBH4tbvQgSH6 #Super secret password
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    networks:
      - auth-network

  keycloak:
    image: docker.io/bitnami/keycloak:latest
    depends_on:
      - postgresql
    restart: unless-stopped
    environment:
      - KEYCLOAK_ADMIN_USER=keycloak.admin
      - KEYCLOAK_ADMIN_PASSWORD=GaP7LDV6Wn6seZ #Super secret password
      - KEYCLOAK_DATABASE_USER=bn_keycloak
      - KEYCLOAK_DATABASE_PASSWORD=vCyBH4tbvQgSH6 #Super secret password
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - auth-network

volumes:
  postgresql_data:
    driver: local

networks:
  auth-network:
    external: true
